[package]
name = "fuse-doc-server"
version = "0.1.0"
authors = ["Kristian Fjeld Hasselknippe <kristian_hasselknippe@outlook.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"